version: 'latest'

services:
  mongo:
    ports:
      - 27017:27017
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: rpg-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      INIT_WAIT_SEC: 3

  client:
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/client/node_modules
    restart: always
    image: rpg/client
    container_name: rpg-client
    build:
      context: .
      dockerfile: ./Dockerfile
      target: client
    environment:
      - CONTAINER=true
    ports:
      - 6789:6789
    depends_on:
      server:
        condition: service_healthy

  server:
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/server/node_modules
    depends_on:
      - mongo
    restart: always
    image: rpg/server
    container_name: rpg-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    environment:
      - DATABASE_URL=mongodb://root:root@mongo:27017/rpg?authSource=admin
    ports:
      - 9876:9876
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9876"]
      interval: 30s
      timeout: 10s
      retries: 5
