version: 'latest'

services:

  client:
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/client/node_modules
      - /usr/src/app/node_modules
    restart: always
    image: rpg/client
    container_name: rpg-client
    build:
      context: .
      dockerfile: ./Dockerfile
      target: client
    environment:
      - CONTAINER=true
    ports:
      - 6789:6789
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6789"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/server/node_modules
      - /usr/src/app/node_modules
    restart: always
    image: rpg/server
    container_name: rpg-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    environment:
      - DATABASE_URL=mongodb+srv://walze:vcxz@cluster0.0akqycw.mongodb.net/test
    ports:
      - 9876:9876
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9876"]
      interval: 30s
      timeout: 10s
      retries: 5
