version: 'latest'

services:
  mongo:
    ports:
      - 27017:27017
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  client:
    restart: always
    image: rpg/client
    container_name: rpg-client
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/client/node_modules
    build:
      context: .
      dockerfile: ./Dockerfile
      target: client
    environment:
      - CONTAINER=true
    ports:
      - 6789:6789
    depends_on:
      - server

  server:
    restart: always
    image: rpg/server
    container_name: rpg-server
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/server/node_modules
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    ports:
      - 9876:9876
