version: 'latest'

services:
  client:
    image: rpg/client
    container_name: rpg-client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - CONTAINER=true
    ports:
      - 6789:6789

  server:
    image: rpg/server
    container_name: rpg-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 9876:9876

  shared:
    image: rpg/shared
    container_name: rpg-shared
    volumes:
      - shared:/app
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  shared:
