version: 'latest'

services:
  client:
    image: rpg/client
    container_name: rpg-client
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    ports:
      - 6789:6789
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  server:
    image: rpg/server
    container_name: rpg-server
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - 9876:9876
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
