version: 'latest'

services:
  mongo:
    ports:
      - 27017:27017
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  client:
    restart: always
    image: rpg/client
    container_name: rpg-client
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    build:
      context: .
      dockerfile: ./Dockerfile
      target: client
    environment:
      - CONTAINER=true
    ports:
      - 6789:6789
    depends_on:
      server:
        condition: service_healthy

  server:
    depends_on:
      - mongo
    restart: always
    image: rpg/server
    container_name: rpg-server
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    ports:
      - 9876:9876
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9876"]
      interval: 30s
      timeout: 10s
      retries: 5
