CREATE TYPE "roles" AS ENUM (
  'admin',
  'private',
  'public',
  'text',
  'roll',
  'reaction',
  'image',
  'audio'
);

CREATE TABLE "channels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "room_id" int,
  "name" varchar
);

CREATE TABLE "channels_roles" (
  "role_id" int,
  "channel_id" int,
  PRIMARY KEY ("role_id", "channel_id")
);

CREATE TABLE "messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" int,
  "user_id" int,
  "channel_id" int,
  "parent_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "rooms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "image" varchar,
  "description" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" roles
);

CREATE TABLE "sheets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "raw" varchar
);

CREATE TABLE "sheets_roles" (
  "role_id" int,
  "sheet_id" int,
  PRIMARY KEY ("role_id", "sheet_id")
);

CREATE TABLE "users" (
  "id" integer PRIMARY KEY,
  "name" varchar,
  "image" varchar,
  "seed" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "users_roles_rooms" (
  "user_id" int,
  "role_id" int,
  "room_id" int,
  PRIMARY KEY ("user_id", "role_id", "room_id")
);

CREATE TABLE "messages_roles" (
  "message_id" int,
  "role_id" int,
  PRIMARY KEY ("message_id", "role_id")
);

ALTER TABLE "channels" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");

ALTER TABLE "channels_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "channels_roles" ADD FOREIGN KEY ("channel_id") REFERENCES "channels" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("channel_id") REFERENCES "channels" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("parent_id") REFERENCES "messages" ("id");

ALTER TABLE "sheets_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "sheets_roles" ADD FOREIGN KEY ("sheet_id") REFERENCES "sheets" ("id");

ALTER TABLE "users_roles_rooms" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_roles_rooms" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "users_roles_rooms" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");

ALTER TABLE "messages_roles" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id");

ALTER TABLE "messages_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
